

const data = [
  {
    "id": 1,
    "company": "TechNova",
    "logo": "technova.png",
    "position": "Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Full Time",
    "location": "Remote",
    "languages": ["JavaScript", "HTML", "CSS"],
    "tools": ["React"],
    "new": true,
    "featured": true
  },
  {
    "id": 2,
    "company": "DataCore",
    "logo": "datacore.png",
    "position": "Backend Engineer",
    "role": "Backend",
    "level": "Midweight",
    "postedAt": "5d ago",
    "contract": "Full Time",
    "location": "Bangalore",
    "languages": ["Python"],
    "tools": ["Django", "PostgreSQL"],
    "new": true,
    "featured": false
  },
  {
    "id": 3,
    "company": "Cloudify",
    "logo": "cloudify.png",
    "position": "DevOps Engineer",
    "role": "DevOps",
    "level": "Senior",
    "postedAt": "1w ago",
    "contract": "Contract",
    "location": "Remote",
    "languages": ["Bash"],
    "tools": ["AWS", "Docker", "Kubernetes"],
    "new": false,
    "featured": true
  },
  {
    "id": 4,
    "company": "PixelWorks",
    "logo": "pixelworks.png",
    "position": "UI/UX Designer",
    "role": "Design",
    "level": "Junior",
    "postedAt": "3d ago",
    "contract": "Part Time",
    "location": "Delhi",
    "languages": [],
    "tools": ["Figma", "Adobe XD"],
    "new": true,
    "featured": false
  },
  {
    "id": 5,
    "company": "SecureNet",
    "logo": "securenet.png",
    "position": "Cybersecurity Analyst",
    "role": "Security",
    "level": "Midweight",
    "postedAt": "6d ago",
    "contract": "Full Time",
    "location": "Hyderabad",
    "languages": ["Python"],
    "tools": ["Wireshark", "Metasploit"],
    "new": false,
    "featured": false
  },
  {
    "id": 6,
    "company": "AppWorks",
    "logo": "appworks.png",
    "position": "Mobile App Developer",
    "role": "Mobile",
    "level": "Senior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Remote",
    "languages": ["Dart"],
    "tools": ["Flutter"],
    "new": false,
    "featured": true
  },
  {
    "id": 7,
    "company": "AI Labs",
    "logo": "ailabs.png",
    "position": "Machine Learning Engineer",
    "role": "AI/ML",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "Pune",
    "languages": ["Python"],
    "tools": ["TensorFlow", "PyTorch"],
    "new": true,
    "featured": true
  },
  {
    "id": 8,
    "company": "FinEdge",
    "logo": "finedge.png",
    "position": "Full Stack Developer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "4d ago",
    "contract": "Full Time",
    "location": "Mumbai",
    "languages": ["JavaScript"],
    "tools": ["Node.js", "React"],
    "new": true,
    "featured": false
  },
  {
    "id": 9,
    "company": "GreenTech",
    "logo": "greentech.png",
    "position": "Data Analyst",
    "role": "Data",
    "level": "Junior",
    "postedAt": "1w ago",
    "contract": "Internship",
    "location": "Remote",
    "languages": ["SQL"],
    "tools": ["Excel", "Power BI"],
    "new": false,
    "featured": false
  },
  {
    "id": 10,
    "company": "NetSolutions",
    "logo": "netsolutions.png",
    "position": "System Administrator",
    "role": "IT",
    "level": "Midweight",
    "postedAt": "3d ago",
    "contract": "Full Time",
    "location": "Chennai",
    "languages": ["Bash"],
    "tools": ["Linux", "Ansible"],
    "new": true,
    "featured": false
  }
];

export default data;